#ifndef _DIRT_XPM_H_
#define _DIRT_XPM_H_

static const char *const dirt_xpm[] = {
"100 100 7 1 ",
"  c None",
". c #050505",
"X c #222329",
"o c #35373F",
"O c #71737B",
"+ c #838488",
"@ c #A9AAB3",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                ......                                              ",
"                                                ......                                              ",
"                            ..........      ....oooooo....                                          ",
"                            ..........      ....oooooo....                                          ",
"                        ....oooooooooo....oooooooooooooooo................                          ",
"                        ....oooooooooo....oooooooooooooooo................                          ",
"                ........oooooooooooooooooooooooooooooooooooooooooooooooooo..                        ",
"                ........oooooooooooooooooooooooooooooooooooooooooooooooooo..                        ",
"              ..OOOOoooooooooooooooooooooooooooooooooooooooooooooooooooooooo........                ",
"              ..OOOOoooooooooooooooooooooooooooooooooooooooooooooooooooooooo........                ",
"            ..OOOOOOooooooooooXXXXXXooooooooXXXXXXXXXXXXXXooooooooooXXooooooooooOOOO..              ",
"            ..OOOOOOooooooooooXXXXXXooooooooXXXXXXXXXXXXXXooooooooooXXooooooooooOOOO..              ",
"            ..OOOOOOXXooooXXXX@@@@@@XXXXooXX@@@@oo@@@@@@@@XXooooXXXX@@XXXXooooooOOOOOO..            ",
"            ..OOOOOOXXooooXXXX@@@@@@XXXXooXX@@@@oo@@@@@@@@XXooooXXXX@@XXXXooooooOOOOOO..            ",
"            ..OOOOOOXXXXXXXX@@@@@@@@@@@@XXXX@@@@oo@@@@@@@@@@XXXX@@@@@@@@@@XXooooOOOOOO..            ",
"            ..OOOOOOXXXXXXXX@@@@@@@@@@@@XXXX@@@@oo@@@@@@@@@@XXXX@@@@@@@@@@XXooooOOOOOO..            ",
"          ..OOOOOOoo@@@@@@oo@@@@@@@@@@++oo@@@@oo@@@@@@@@@@@@@@oo@@@@@@@@@@@@XXXXOOOOOO..            ",
"          ..OOOOOOoo@@@@@@oo@@@@@@@@@@++oo@@@@oo@@@@@@@@@@@@@@oo@@@@@@@@@@@@XXXXOOOOOO..            ",
"        ..OOOOOOoo@@@@@@@@oo@@@@@@@@++oo@@@@@@++oo++@@@@++++oo++++@@@@@@oooooo@@ooOOOOOO..          ",
"        ..OOOOOOoo@@@@@@@@oo@@@@@@@@++oo@@@@@@++oo++@@@@++++oo++++@@@@@@oooooo@@ooOOOOOO..          ",
"        ..OOOOoo++++@@@@oo++++@@@@++++oo++@@@@++oo++++++++oo++++++++++oo@@@@@@@@@@ooOOOO..          ",
"        ..OOOOoo++++@@@@oo++++@@@@++++oo++@@@@++oo++++++++oo++++++++++oo@@@@@@@@@@ooOOOO..          ",
"        ..OOoo++++++++oo++++++++++++++oo++++++++ooOOOOOOooOO++++++++OOoo++@@@@@@@@@@ooOOOO..        ",
"        ..OOoo++++++++oo++++++++++++++oo++++++++ooOOOOOOooOO++++++++OOoo++@@@@@@@@@@ooOOOO..        ",
"      ..OOOOooOO++OOOOooOO++++++++OOOOoo++++++OOOOooOOooOOOOOOOOOOOOOOooOO++++++++++++ooOO..        ",
"      ..OOOOooOO++OOOOooOO++++++++OOOOoo++++++OOOOooOOooOOOOOOOOOOOOOOooOO++++++++++++ooOO..        ",
"      ..OOOOOOooOOOOooOOOOOOOOOOOOOOOOooOOOOOOOOOOooOOooOOOOOOOOOOOOooOOOOOOOOOOOO++++++oo..        ",
"      ..OOOOOOooOOOOooOOOOOOOOOOOOOOOOooOOOOOOOOOOooOOooOOOOOOOOOOOOooOOOOOOOOOOOO++++++oo..        "
};

#endif
